//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 11:18:15 PM EAT 
//


package com.zara.Zara.integrations.test.products;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProductID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProductNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MakeFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="FinishedGoodsFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SafetyStockLevel" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="ReorderPoint" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="StandardCost" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="ListPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SizeUnitMeasureCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WeightUnitMeasureCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="DaysToManufacture" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ProductLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Style" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProductSubcategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ProductModelID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SellStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="SellEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="DiscontinuedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="rowguid" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="ModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "productID",
    "name",
    "productNumber",
    "makeFlag",
    "finishedGoodsFlag",
    "color",
    "safetyStockLevel",
    "reorderPoint",
    "standardCost",
    "listPrice",
    "size",
    "sizeUnitMeasureCode",
    "weightUnitMeasureCode",
    "weight",
    "daysToManufacture",
    "productLine",
    "clazz",
    "style",
    "productSubcategoryID",
    "productModelID",
    "sellStartDate",
    "sellEndDate",
    "discontinuedDate",
    "rowguid",
    "modifiedDate"
})
public class Product {

    @XmlElement(name = "ProductID")
    protected int productID;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "ProductNumber")
    protected String productNumber;
    @XmlElement(name = "MakeFlag", required = true, type = Boolean.class, nillable = true)
    protected Boolean makeFlag;
    @XmlElement(name = "FinishedGoodsFlag", required = true, type = Boolean.class, nillable = true)
    protected Boolean finishedGoodsFlag;
    @XmlElement(name = "Color")
    protected String color;
    @XmlElement(name = "SafetyStockLevel", required = true, type = Short.class, nillable = true)
    protected Short safetyStockLevel;
    @XmlElement(name = "ReorderPoint", required = true, type = Short.class, nillable = true)
    protected Short reorderPoint;
    @XmlElement(name = "StandardCost", required = true, nillable = true)
    protected BigDecimal standardCost;
    @XmlElement(name = "ListPrice", required = true, nillable = true)
    protected BigDecimal listPrice;
    @XmlElement(name = "Size")
    protected String size;
    @XmlElement(name = "SizeUnitMeasureCode")
    protected String sizeUnitMeasureCode;
    @XmlElement(name = "WeightUnitMeasureCode")
    protected String weightUnitMeasureCode;
    @XmlElement(name = "Weight", required = true, nillable = true)
    protected BigDecimal weight;
    @XmlElement(name = "DaysToManufacture", required = true, type = Integer.class, nillable = true)
    protected Integer daysToManufacture;
    @XmlElement(name = "ProductLine")
    protected String productLine;
    @XmlElement(name = "Class")
    protected String clazz;
    @XmlElement(name = "Style")
    protected String style;
    @XmlElement(name = "ProductSubcategoryID", required = true, type = Integer.class, nillable = true)
    protected Integer productSubcategoryID;
    @XmlElement(name = "ProductModelID", required = true, type = Integer.class, nillable = true)
    protected Integer productModelID;
    @XmlElement(name = "SellStartDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sellStartDate;
    @XmlElement(name = "SellEndDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sellEndDate;
    @XmlElement(name = "DiscontinuedDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar discontinuedDate;
    @XmlElement(required = true, nillable = true)
    protected String rowguid;
    @XmlElement(name = "ModifiedDate", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifiedDate;

    /**
     * Gets the value of the productID property.
     * 
     */
    public int getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     */
    public void setProductID(int value) {
        this.productID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the productNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductNumber() {
        return productNumber;
    }

    /**
     * Sets the value of the productNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductNumber(String value) {
        this.productNumber = value;
    }

    /**
     * Gets the value of the makeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMakeFlag() {
        return makeFlag;
    }

    /**
     * Sets the value of the makeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMakeFlag(Boolean value) {
        this.makeFlag = value;
    }

    /**
     * Gets the value of the finishedGoodsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFinishedGoodsFlag() {
        return finishedGoodsFlag;
    }

    /**
     * Sets the value of the finishedGoodsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFinishedGoodsFlag(Boolean value) {
        this.finishedGoodsFlag = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the safetyStockLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSafetyStockLevel() {
        return safetyStockLevel;
    }

    /**
     * Sets the value of the safetyStockLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSafetyStockLevel(Short value) {
        this.safetyStockLevel = value;
    }

    /**
     * Gets the value of the reorderPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getReorderPoint() {
        return reorderPoint;
    }

    /**
     * Sets the value of the reorderPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setReorderPoint(Short value) {
        this.reorderPoint = value;
    }

    /**
     * Gets the value of the standardCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStandardCost() {
        return standardCost;
    }

    /**
     * Sets the value of the standardCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStandardCost(BigDecimal value) {
        this.standardCost = value;
    }

    /**
     * Gets the value of the listPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getListPrice() {
        return listPrice;
    }

    /**
     * Sets the value of the listPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setListPrice(BigDecimal value) {
        this.listPrice = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the sizeUnitMeasureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizeUnitMeasureCode() {
        return sizeUnitMeasureCode;
    }

    /**
     * Sets the value of the sizeUnitMeasureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizeUnitMeasureCode(String value) {
        this.sizeUnitMeasureCode = value;
    }

    /**
     * Gets the value of the weightUnitMeasureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightUnitMeasureCode() {
        return weightUnitMeasureCode;
    }

    /**
     * Sets the value of the weightUnitMeasureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightUnitMeasureCode(String value) {
        this.weightUnitMeasureCode = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }

    /**
     * Gets the value of the daysToManufacture property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDaysToManufacture() {
        return daysToManufacture;
    }

    /**
     * Sets the value of the daysToManufacture property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDaysToManufacture(Integer value) {
        this.daysToManufacture = value;
    }

    /**
     * Gets the value of the productLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductLine() {
        return productLine;
    }

    /**
     * Sets the value of the productLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductLine(String value) {
        this.productLine = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the productSubcategoryID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProductSubcategoryID() {
        return productSubcategoryID;
    }

    /**
     * Sets the value of the productSubcategoryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProductSubcategoryID(Integer value) {
        this.productSubcategoryID = value;
    }

    /**
     * Gets the value of the productModelID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProductModelID() {
        return productModelID;
    }

    /**
     * Sets the value of the productModelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProductModelID(Integer value) {
        this.productModelID = value;
    }

    /**
     * Gets the value of the sellStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSellStartDate() {
        return sellStartDate;
    }

    /**
     * Sets the value of the sellStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSellStartDate(XMLGregorianCalendar value) {
        this.sellStartDate = value;
    }

    /**
     * Gets the value of the sellEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSellEndDate() {
        return sellEndDate;
    }

    /**
     * Sets the value of the sellEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSellEndDate(XMLGregorianCalendar value) {
        this.sellEndDate = value;
    }

    /**
     * Gets the value of the discontinuedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDiscontinuedDate() {
        return discontinuedDate;
    }

    /**
     * Sets the value of the discontinuedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDiscontinuedDate(XMLGregorianCalendar value) {
        this.discontinuedDate = value;
    }

    /**
     * Gets the value of the rowguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowguid() {
        return rowguid;
    }

    /**
     * Sets the value of the rowguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowguid(String value) {
        this.rowguid = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifiedDate() {
        return modifiedDate;
    }

    /**
     * Sets the value of the modifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifiedDate(XMLGregorianCalendar value) {
        this.modifiedDate = value;
    }

}
